### ISSUE TITLE
netstandard project "Could not find a part of the path...App.xaml"

### ISSUE THREAD

**Issue by lhughey** [OYIon/XamarinFormsLive#10]
I'm testing the project with a netstandard 1.4 project, and I'm unable to build the application when the LiveXaml nuget is installed.  The error that I'm getting is below.

> >obj\Debug\netstandard1.4\obj\Debug\netstandard1.4\App.xaml : error : Could not find a part of the path 'Y:\Repos\Source\projectName\projectName\projectName.Core\obj\Debug\netstandard1.4\obj\Debug\netstandard1.4\App.xaml'.

I've tried cleaning the project and manually deleted the bin/obj folders.

I'm using:
Visual studio 2017 15.3
XamForms 2.35pre-6
netstandard 1.4
I've included and excluded XamlCompilation options with no change in behavior

The netstandard package fallback has been set as "portable-win+net45+wp8+win81+wpa8"

The project structure is 
ProjectName
-ProjectName.Core
-ProjectName.Android
-ProjectName.iOS
-ProjectName.UWP

I've not tried running the project on any target platform as I'm unable to compile the core project.

**Comment by ionoy** [comment]
Can you run a full rebuild and paste the output here?

**Comment by lhughey** [comment]
The problem seems to be the path of the generated App.xaml in the obj folder. It seems that LiveXaml  is looking for the App.xaml in the following path with this project.

Y:\Repos\Source\ProjectName\ProjectName\ProjectName.Core\obj\Debug\netstandard1.4\obj\Debug\netstandard1.4\App.xaml

The actual path is:
Y:\Repos\Source\ProjectName\ProjectName\ProjectName.Core\obj\Debug\netstandard1.4\App.xaml

The **abbreviated**  output is:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'Y:\Repos\Source\ProjectName\ProjectName\ProjectName.Core\obj\Debug\netstandard1.4\obj\Debug\netstandard1.4\App.xaml'.	ProjectName	Y:\Repos\Source\ProjectName\ProjectName\BudgetPOC.Core\obj\Debug\netstandard1.4\obj\Debug\netstandard1.4\App.xaml	1	

**You can download my verbose output (14mb) here**: https://www.dropbox.com/s/bipzocydl6fmwj9/LiveXamlErrorOutput.txt?dl=0

**Comment by ionoy** [comment]
Hmm, I still can't understand why is the file path wrong. Would it be possible for you to send me your "ProjectName.Core" project, with everything but App.xaml removed? I tried creating a NetStandard project on my machine and it worked fine with LiveXAML.

Thank you!

**Comment by ionoy** [comment]
It seems to me, that this problem is about the updated *.csproj file format. It is referencing all the XAML files it can find since there are no explicit `<EmbeddedResource />` nodes. What I don't get is why on my machine it only references "original" files and not the ones under `obj`.

**Comment by lhughey** [comment]
I just shot you a zip file to your gmail account.  I'll get around to trying another NetStandard Xamarin project later today.

I'm definitely thinking it has something to do with the updated project format.  The project that I sent to you was a project that I moved existing content over from a PCL project.  Its possible that there are some  elements in the .csproj file that you're not expecting, and maybe can be removed.

**Comment by lhughey** [comment]
**BREAK THROUGH: The issue is on my project NOT with the  LiveXAML.**  It looks like the the "obj" folder was being added to the project by automatically causing all kinds of troubles.  I had this happen on two projects.  I've never seen this happen but it could be caused by the compile directive to to compile .xaml.cs files in the ItemGroup??

The ItemGroup section in my .csproj file was as such:
` <ItemGroup>
    
    <None Remove="**\*.xaml" />
    <Compile Update="**\*.xaml.cs" DependentUpon="%(Filename)" />
    <EmbeddedResource Include="**\*.xaml" SubType="Designer" Generator="MSBuild:UpdateDesignTimeXaml" />
  </ItemGroup>`

My project ended up with the following ItemGroup once I removed the obj folder that was automatically added to the project by VS.  
`  <ItemGroup>
    
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="**\*.xaml" />
    <None Remove="obj\**" />    
    <Compile Update="**\*.xaml.cs" DependentUpon="%(Filename)" />
    <EmbeddedResource Include="**\*.xaml" SubType="Designer" 
 Generator="MSBuild:UpdateDesignTimeXaml" />
  </ItemGroup>`

**Comment by ionoy** [comment]
Sorry I couldn't answer earlier. 

Did you create your NetStandard project from scratch and copied files from PCL? Because when I do that, I get an almost empty project file that only has NuGet references in it. All other files are being implicitly referenced. 

Removing files with a wildcard is certainly a workaround. But do you have to do that by hand? I still don't exactly understand how this situation occurs and why other tools are OK with it.

**Comment by lhughey** [comment]
Yes, I did edit the ItemGroup section posted in my last reply by hand.  It adds the ability for VS to group Xaml.cs with the Xaml files.

**Comment by ionoy** [comment]
Frankly, I'm not sure how to proceed with this issue. Does LiveXAML work with your modifications?

**Comment by lhughey** [comment]
It does work.  I now think this issue is one of configuration and not a problem with LiveXAML.  Thanks for looking at it.

**Comment by ionoy** [comment]
Great!
