### ISSUE TITLE
Works in one project, but doesn't work in another one

### ISSUE THREAD

**Issue by vlkam** [OYIon/XamarinFormsLive#11]
Thanks for awesome LiveXAML, it's really impressive.
But I have an issue, LiveXAML works in one project, but doesn't work in another
I guess that it just not started in the second project/
I'd be very appriciate if you can help me with this issue
Logs for the projects attached 
[LiveXAML doesnt work in that project.txt](https://github.com/OYIon/XamarinFormsLive/files/1248172/LiveXAML.doesnt.work.in.that.project.txt)
[LiveXAML works in this project.txt](https://github.com/OYIon/XamarinFormsLive/files/1248173/LiveXAML.works.in.this.project.txt)

LiveXAML extension 1.3.21
nuget 1.2.15

Visual Studio
Microsoft Visual Studio Community 2017  (2)
Version 15.3.2
VisualStudio.15.Release/15.3.2+26730.10
Microsoft .NET Framework
Version 4.7.02046
Installed Version: Community
Visual Basic 2017   00369-60000-00001-AA467
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA467
Microsoft Visual C# 2017

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DPack   3.11.3
DPack for Visual Studio
Copyright © 2004-2017 USysWare, Inc.
For more information, visit http://www.usysware.com/dpack/ or contact us at support@usysware.com
JavaScript support via JavaScript Parser extension by Oleksandr Boiko
File Nesting   2.6.67
Automatically nest files based on file name and enables developers to nest and unnest any file manually
GitHub.VisualStudio   2.2.0.11
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.
Mono Debugging for Visual Studio   4.6.8-pre (ec7034f)
Support for debugging Mono processes with Visual Studio.
NuGet Package Manager   4.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
SettingsWindow Extension   1.0
SettingsWindow Visual Studio Extension Detailed Info
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
Xamarin   4.6.0.299 (b63523e27)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin.Android SDK   7.4.0.21 (2851083)
Xamarin.Android Reference Assemblies and MSBuild support.
Xamarin.iOS and Xamarin.Mac SDK   10.12.0.20 (80b8487)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by ionoy** [comment]
Thanks for the feedback!

Can you please post the Output from the debugging session? `LiveXAML doesnt work in that project.txt` only shows the build.

**Comment by vlkam** [comment]
Yes, of course, I'm sorry
Here is this


[log.txt](https://github.com/OYIon/XamarinFormsLive/files/1248185/log.txt)

**Comment by ionoy** [comment]
Are you sure that `LiveXAML` package is installed in this project? I don't see any XAML files being registered on initialization.

**Comment by vlkam** [comment]
Yes, unfortunately I'm sure. I tested in 5 times 
Here is the project file for PCL part of project (I renamed this in txt)
[JCabinet.csproj.txt](https://github.com/OYIon/XamarinFormsLive/files/1248230/JCabinet.csproj.txt)

**Comment by ionoy** [comment]
It seems like everything is in place. 
Please try rebuilding with the Output verbosity set to `Diagnostic`. You can change it in `Tools -> Options -> Projects and Solutions -> Build and Run -> MSBuild project build output verbosity`

Thanks!

**Comment by vlkam** [comment]
Very interesting, seems as there is some interesting lines
In this project I have some custom Solution Configurations, for example Jr-Debug for Jr app in debug mode
[Deploy.txt](https://github.com/OYIon/XamarinFormsLive/files/1248274/Deploy.txt)
[rebulid PCL.txt](https://github.com/OYIon/XamarinFormsLive/files/1248273/rebulid.PCL.txt)
[rebuild Andriod.txt](https://github.com/OYIon/XamarinFormsLive/files/1248275/rebuild.Andriod.txt)

**Comment by ionoy** [comment]
LiveXAML only works in Debug configuration, which it checks with this condition `'$(Configuration)' == 'Debug'`

It seems like this isn't a good way to do it. There is also a `DISABLE_XAMARINFORMSLIVE` compilation symbol. Maybe it is sufficient, and LiveXAML shouldn't depend on Debug? What do you think?

**Comment by ionoy** [comment]
Anyway, I have uploaded LiveXAML 1.2.16 to NuGet. It will be visible in a few minutes and should mitigate your issue. Please tell me if it works.

Thank you!

**Comment by vlkam** [comment]
Yes, this project hasn't Debug configuration, but has Jr-Debug, Fr-Debug etc...
I'm detecting Debug config that way  Condition="$(Configuration.Contains('Debug'))"
Perhaps it is not best way for LiveXAML

Thanks a lot for your help! I am very grateful

**Comment by ionoy** [comment]
I'm glad it finally works for you!

Since you helped me identify this issue, you are eligible for a good discount if you ever decide to purchase a license.

**Comment by vlkam** [comment]
Yes, It's working!
It just amazing
Of course, I did purchase a monthly subscription
Thank you very much

**Comment by ionoy** [comment]
Great, thank you!
