### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by james-lavery** [OYIon/XamarinFormsLive#12]
I've downloaded the VS For Mac extension - this has given me _LiveXAML.1.0.mpack_ in my downloads folder.

How do I install this as an extension in Visual Studio For Mac?

**Comment by ionoy** [comment]
Hello James,

Open Extensions window, there will be "install from disk" link or something like this. I don't have a Mac near me at the moment, so I can't check. 

Unfortunately, it is impossible right now to publish extension to the official VS4Mac marketplace.

After that, install LiveXAML NuGet package as described here: https://marketplace.visualstudio.com/items?itemName=ionoy.XamarinFormsLive-18843

**Comment by james-lavery** [comment]
HI - thanks, just found it myself. I was thinking it was an 'external tool' rather than an Extension!
