### ISSUE TITLE
periodically throws exception SocketException : Connection timed out

### ISSUE THREAD

**Issue by vlkam** [OYIon/XamarinFormsLive#14]
Exception:
System.Net.Sockets.SocketException: Connection timed out occurred

![exception_1](https://user-images.githubusercontent.com/7336057/29772447-8baeceb2-8c01-11e7-8edf-414675303b49.png)

[log.txt](https://github.com/OYIon/XamarinFormsLive/files/1256679/log.txt)

**Comment by ionoy** [comment]
Thanks for the feedback!

Can you post a callstack?

**Comment by vlkam** [comment]
Yes, of couse

 	[External Code]		Annotated Frame
>	0x17 in XamarinFormsLive.SocketProxy.EndReceive at C:\Junior\Junior\Mobile\JuniorClientApplication\packages\LiveXAML.1.2.16\build\minified.cs:270,65	C#	Symbols loaded.
 	0x10 in XamarinFormsLive.G.x at C:\Junior\Junior\Mobile\JuniorClientApplication\packages\LiveXAML.1.2.16\build\minified.cs:245,47	C#	Symbols loaded.
 	0xD in XamarinFormsLive.G. at C:\Junior\Junior\Mobile\JuniorClientApplication\packages\LiveXAML.1.2.16\build\minified.cs:238,65	C#	Symbols loaded.

**Comment by ionoy** [comment]
Thanks!

**Comment by ionoy** [comment]
What emulator are you using?

**Comment by vlkam** [comment]
Visual Studio Emulator for Android

**Comment by ionoy** [comment]
It seems like the issue should be fixed now. Please try updating to 1.2.21 version of NuGet package.

BTW, I see that LiveXAML resorts to using UDP because it cannot connect to the server. Do you have LiveXAML.Server running while debugging the application?

**Comment by vlkam** [comment]
O.. it's my fault, I forgot to update nuget package to last version. Sorry
But after update there is a new exception :

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.

Call stack
>	0x17 in __livexaml.R.EndReceive at C:\Junior\Junior\Mobile\JuniorClientApplication\packages\LiveXAML.1.2.21\build\minified.cs:263,28	C#	Symbols loaded.
 	0x10 in __livexaml.N.x at C:\Junior\Junior\Mobile\JuniorClientApplication\packages\LiveXAML.1.2.21\build\minified.cs:238,52	C#	Symbols loaded.
 	0xD in __livexaml.N. at C:\Junior\Junior\Mobile\JuniorClientApplication\packages\LiveXAML.1.2.21\build\minified.cs:232,32	C#	Symbols loaded.

**Comment by vlkam** [comment]
Where I can see LiveXAML.Server  ?
I tried to find it in processes list of Task Manager, but cannot find it

**Comment by ionoy** [comment]
It starts when you open a project. Should be in the Task Manager.

![image](https://user-images.githubusercontent.com/592624/29776680-19ee2d8e-8c12-11e7-8cf8-c96faa626737.png)

**Comment by vlkam** [comment]
Thanks!
LiveXAML.Server is running

**Comment by ionoy** [comment]
I have uploaded a new package to NuGet (1.2.25)
This new version shouldn't throw anything if it cannot connect to the server.

Although, you only see these exceptions because you have enabled "Break when thrown." This means that even if the exception is handled by LiveXAML, you still see it as a regular unhandled exception.

![image](https://user-images.githubusercontent.com/592624/29779232-965603a8-8c1a-11e7-9436-fc6ebb43d1b3.png)

**Comment by vlkam** [comment]
Thank you very much !
