### ISSUE TITLE
Exception when using Automation Ids

### ISSUE THREAD

**Issue by shorlick** [OYIon/XamarinFormsLive#16]
I have just installed LiveXAML, and when trying to make changes on a page that uses Automation Ids, I get the following exception:
"Exception has been thrown by the target of an invocation.  AutomationId may only be set one time."

This occurs even though I am not changing the Automation Ids.  If I remove all Automation Ids then I don't get the exception.

https://bugzilla.xamarin.com/show_bug.cgi?id=40817

**Comment by ionoy** [comment]
Thanks for the feedback!

Can you show me the code where AutomationId is set?

**Comment by shorlick** [comment]
Here is a simple example:

`<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="UI.SettingsView" Icon ="fa-bars" Title="Settings" AutomationId="settingsViewContentPage"  Padding="0">
    <ContentPage.Content>
    <StackLayout Orientation="Vertical"  HorizontalOptions="FillAndExpand" VerticalOptions="StartAndExpand">
        <BoxView Color="Gray" HorizontalOptions="FillAndExpand" HeightRequest="40"/>
        <Button Command="{Binding LogoutCommand}"   Text="Sign Out"  AutomationId="LogoutButton"/>
    </StackLayout>
    </ContentPage.Content>
</ContentPage>`

I have realised that the error only occurs if I have an AutomationId on the ContentPage itself - the controls within the page can happily have an AutomationId.   (Thinking about it, I am unsure if our ContentPage tags even need an AutomationID or not?)

Also just wanted to say I am super impressed by this project - I am currently having to make a lot of small UI tweaks and this is going to make my life a million times easier.  So thank you!!

**Comment by ionoy** [comment]
I have uploaded the update to LiveXAML NuGet package. Please try it and see if it fixes your issue. 

Thanks!

**Comment by shorlick** [comment]
Yes that fixes it!  Thank you!
