### ISSUE TITLE
LiveXaml not working in physical device

### ISSUE THREAD

**Issue by AMARMATHUR** [OYIon/XamarinFormsLive#29]
I am trying to edit xaml file with LiveXaml but nothing happend. I am getting folleowing log:

> [0:] XL: Handshake connection timed out
> Thread started: <Thread Pool> #8
> [0:] XL: Handshake server unreachable 169.254.80.80
> [0:] XL: Connecting to the handshake server 10.0.2.2
> [0:] XL: Handshake connection timed out
> Thread started: <Thread Pool> #9
> [0:] XL: Handshake server unreachable 10.0.2.2
> [0:] XL: Connecting to the handshake server 10.0.3.2
> [0:] XL: Handshake connection timed out
> [0:] XL: Handshake server unreachable 10.0.3.2
> [0:] XL: Failed to find find a handshake server
> [0:] XL: Trying to use UDP connection

**Comment by gabrielrobert** [comment]
+1

**Comment by ionoy** [comment]
Can you post full Output window dump? You can filter out everything that doesn't start with "XL".

**Comment by gabrielrobert** [comment]
Of course @ionoy.

[Build logs](https://pastebin.com/xpeZzWak)
[Debug logs](https://pastebin.com/r4818xCY)

Core project PCL -> LiveXAML v2.1.1
iOs project -> LiveXAML v2.1.1


TCP ports open: 50530, 53031, 53032, 50531, 50532
UDP ports open: 50530, 53031, 53032, 50531, 50532

**Comment by ionoy** [comment]
It seems that device can't connect to 10.0.0.228. Is it located on the same network as the device?

**Comment by gabrielrobert** [comment]
@ionoy Yes, of course. This is our Mac build machine to deploy on iOs physical devices. I'm trying to use LiveXAML on a Windows machine. Also, Xamarin Mac agent is properly connected.

**Comment by ionoy** [comment]
Is the iOS device itself connected to the same network through WiFi?

**Comment by gabrielrobert** [comment]
Oh god, that was the problem. For some reasons, my device got disconnected from the WiFi. Thank you! :)

**Comment by ionoy** [comment]
You're welcome!

**Comment by ionoy** [comment]
@AMARMATHUR Do you still have this problem?
