### ISSUE TITLE
Genymotion support

### ISSUE THREAD

**Issue by Evolutionlab** [OYIon/XamarinFormsLive#3]
Have you considered adding support to genymotion? https://www.genymotion.com/fun-zone/
Sure, its not a priority: xamarin forms live works very well with Google AVD Emulators.

I was thinking about Genymotion 'cause my next development PC could be an AMD (that doesnt support HAXM, so Google AVDs are slow as hell on windows).

**Comment by ionoy** [comment]
Is it possible to use Genymotion with Visual Studio? How does development cycle look like if someone uses it?

**Comment by Evolutionlab** [comment]
Genymotion comes with visual studio support. 
When you start a virtual machine with Genymotion you can debug your app from the Visual Studio "play"  button:

![2017-06-30_17h49_02](https://user-images.githubusercontent.com/8319337/27743498-7cbdfaea-5dbc-11e7-925b-5fb1c0421169.png)

If the VM is stopped, though, you cant see it in Visual Studio

**Comment by ionoy** [comment]
Alright, I'll take a look at it after I'm done with iOS support.  

Thanks for the suggestion!

**Comment by Evolutionlab** [comment]
Nice. thanks for your great work.

As a starting point you can try to connect the listener to 10.0.3.2 or 192.168.56.1

**Comment by ionoy** [comment]
Will try 👍

**Comment by Evolutionlab** [comment]
Just a quick update on this. Go with 10.0.3.2 it will work for sure :) Ti should be an easy task.

It would be great to have the option to manually specify what ip address(es) the emulator need to connect to xlserver. Maybe in the extensions options.
This would introduce greater flexibility for future updates on emulators.

**Comment by ionoy** [comment]
Thanks for the tip! I've tried 10.0.3.2 and it works well. 

New package release is already uploaded to NuGet, you can try it when you have a chance. 

About separate configuration for emulator pass-thru IP addresses, it is certainly doable. But frankly, I don't want to get into it now. I will create a separate issue though.

**Comment by ionoy** [comment]
@Evolutionlab Did you have a chance to try it yet?

**Comment by Evolutionlab** [comment]
Planning to test it tomorrow, i'm in vacation now :)

**Comment by Evolutionlab** [comment]
Sorry for the delay. I confirm that is working. I tried several things (app.xaml resources, styling, native embedding, ecc...), everything is working fine. Good Job!
