### ISSUE TITLE
Not working with with other build configuration

### ISSUE THREAD

**Issue by brimmy11** [OYIon/XamarinFormsLive#32]
LiveXAML works perfectly when my build configuration is set to Debug but when I change it to a different debugging configuration (lets say FranceDebug) I get the error below
![image](https://user-images.githubusercontent.com/26055630/32477800-cec96440-c3bb-11e7-838f-d6a5aef85e4c.png)

**These are my build configurations:**
[build_configs.txt](https://github.com/OYIon/LiveXAML/files/1448748/build_configs.txt)

**Comment by ionoy** [comment]
This issue should be resolved in the latest Visual Studio extension. Do you still have problems with it?
