### ISSUE TITLE
App crashes on  Xamarin.Forms.2.5.0.91635

### ISSUE THREAD

**Issue by bentmar** [OYIon/XamarinFormsLive#33]
```<?xml version="1.0" encoding="utf-8" ?>
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="stylesBug.Day">
    
    <Color x:Key="Primary">#2d77aa</Color>
    
</ResourceDictionary>
```

When you new up this xaml with var d = new Day();

App crashes on Xamarin.Forms.2.5.0.91635. 

Removing livexaml is the only way i solved this issue.

https://forums.xamarin.com/discussion/107000/xamlparseexception-not-a-bindableobject

**Comment by ionoy** [comment]
Ouch, sorry for that!

I've fixed it in LiveXAML 1.3.14

Please see if it works now.
