### ISSUE TITLE
XL: Constructor initializing failed.

### ISSUE THREAD

**Issue by marcojak** [OYIon/XamarinFormsLive#45]
I'm having troubles with LiveXAML.
I'm testing it before buying it for my team but it does't seem to work.

I tested it with a very simple XAML and it worked but then I tested it with my Login XAML page: when I run the emulator I can see the page, then if I try to do a change to the XAML I receive this message and the page on the emulator becomes completely white.

My XAML page is really easy and the only thing more "complex" is the it inherits from a base page.

How Can I fix it?

**Comment by ionoy** [comment]
Hello Marco,

Thanks for the feedback! Would it be possible for you to create a small sample demonstrating the issue?

Thank you!

**Comment by marcojak** [comment]
Hi Mihhail, I think I've solved.

I didn't have a parameterless contructor and that was the first problem, then I added one but I forgot to call InitializeComponent() and that was the error. After I added that call everything worked well.

Ps. Very good tool

**Comment by ionoy** [comment]
Thank you for clearing that up!
