### ISSUE TITLE
Doesn't Update With Rider IDE

### ISSUE THREAD

**Issue by JohnLouderback** [OYIon/XamarinFormsLive#49]
When saving XAML files from Rider, I can't get the UI to update. I have Visual Studio running in the background with LiveXaml extension and package installed. I have the update if not debugging checkbox checked as well. If I go into Visual Studio and make changes and save the file (while debugging from Rider), I can get the changes to show, but they never show when saving changes from Rider itself. There don't appear to be any errors in the debug logs.

**Comment by JohnLouderback** [comment]
I'm going to leave this here and open because I still believe it's a bug and because it almost caused me to decide not to buy a license, but it appears to be working properly now that I've purchased a license.

**Comment by ionoy** [comment]
Hello @JohnLouderback,

It shouldn't be the issues with trial/paid license. Maybe Visual Studio restart helped, or something like this. 

Anyway, I'm glad it works now.
