### ISSUE TITLE
Disable for release

### ISSUE THREAD

**Issue by MosCD** [OYIon/XamarinFormsLive#50]
Yes , I found that in the FAQ
You can define `DISABLE_XAMARINFORMSLIVE` compilation symbol for Release or other configuration that doesn't require LiveXAML.

Bu I don't know how to do it in VisualStudio Mac 2017
Please step by step for iOS and Android projects

**Comment by ionoy** [comment]
Hello @MosCD 

You can find it here:

![image](https://user-images.githubusercontent.com/592624/36023256-7e2ee280-0d94-11e8-8c9d-df73ed2c71df.png)

**Comment by MosCD** [comment]
thank you for help
