### ISSUE TITLE
Does not try connecting to correct IP addresses and fails to find handshake server

### ISSUE THREAD

**Issue by Adam--** [OYIon/XamarinFormsLive#57]
My computer has is connected to two networks, one wired and one wireless, with IP addresses 10.0.2.29 and 192.168.1.121. My android device is also connected to the wireless network and has IP address 192.168.1.141.

When I deploy to my android device I get the following output where the IP addresses that LiveXAML is trying to connect to doesn't match up.

```
[0:] XL: Connecting to the handshake server 127.0.0.1
[0:] XL: Handshake connection failed for 127.0.0.1 One or more errors occurred.
[0:] XL: Handshake server unreachable 127.0.0.1
[0:] XL: Connecting to the handshake server 169.254.80.80
[0:] XL: Handshake connection timed out
[0:] XL: Connecting to the handshake server 10.0.2.2
[0:] XL: Handshake connection timed out
[0:] XL: Handshake server unreachable 10.0.2.2
[0:] XL: Connecting to the handshake server 10.0.3.2
[0:] XL: Handshake connection timed out
[0:] XL: Handshake server unreachable 10.0.3.2
[0:] XL: =============== LiveXAML Important Information ===============
[0:] XL: Failed to find find a handshake server
1) Is phone connected to the same WiFi network?
2) Are ports 53031 and 53032 opened in firewall?
3) If On Windows, make sure that xlserver.exe is running
[0:] XL: ==============================================================
```

I've tried the following:
- Upgraded to latest stable LiveXAML NuGet 2.1.36 with VS extension 1.7.5
- Killed xlserver.exe and restarted Visual Studio
- Disabled the firewall on the wifi router
- Checked PC firewall settings for xlserver.exe and allowed it through the firewall. There were a lot of entries.
- Uninstalled app and mono from android device, cleaned solution, manually deleted bin and obj
- Removed irrelevant network adapters (lots of stuff from emulators) and restarted everything

**Comment by ionoy** [comment]
Please try to disable the "10.0.2.29" interface and rebuild the application. Does it help?

**Comment by Adam--** [comment]
Thanks for the quick reply Mihhail.

I disabled the interface, cleaned, built and started debugging and was able to connect.
I enabled the interface and started debugging and was able to connect.
With the interface enabled, I cleaned, built and started debugging and was **not** able to connect.
I disabled the interface and started debugging and was **not** able to connect.

I'm not understanding what's happening here. Is there anything I can do? I need that interface enabled. It's how I connect to my work network and the internet. Unfortunately, I'm not able to connect the Android device to this network.

Is it related to rebuilding the application somehow?
Are there any VPN related nuances that could cause issues?

**Comment by ionoy** [comment]
During the rebuild, LiveXAML MSBuild Task hard codes host PC IP address into the application. To guess the IP, it queries the 8.8.8.8 address and looks at which interface was used for this request. Sometimes it guesses wrong. I might need to add something like optional `livexaml.config` file for users to override the IP address. What do you think?

**Comment by Adam--** [comment]
In my configuration, I have the device connected to a network that doesn't have internet access. It's literally just an Asus router I have sitting on my desk.

I'm a fan of being able to configure defaults when they fail. The configuration would need to be machine specific and not part of the repo.

Are there any down sides to trying all ip addresses regardless of which interface queries 8.8.8.8? 
I'd like to see how my computer behaves when querying 8.8.8.8. How can I do that?

Another option for locating the server would be mDNS/bonjour/zeroconf.

**Comment by ionoy** [comment]
Well, it is possible to hard-code all of the available IP addresses I guess. 

I'll also research other possible techniques for doing this stuff. Querying the public IP address felt like the easiest option at the time.

In the meantime, you can replace XamarinLive.Build.dll in the `packages` with the attached file. With this build, you can create a `livexaml.config` file in your project root with the following content.

```
hostip=x.x.x.x
```

Where `x.x.x.x` is your IP address. I realize that this is user specific override, but at least you will be able to use LiveXAML from now on.

[XamarinLive.Build.zip](https://github.com/OYIon/LiveXAML/files/2189898/XamarinLive.Build.zip)

**Comment by Adam--** [comment]
Thanks for the workaround, your help is much appreciated as always!

**Comment by Adam--** [comment]
I replaced the dll and placed a livexaml.config file with the correct ip at the root (same level as .sln)

![image](https://user-images.githubusercontent.com/2179171/42656202-8272a11c-85ec-11e8-9e6b-ba0d203bdc18.png)


When building I get an error
```
..\packages\LiveXAML.2.1.36\build\LiveXAML.targets(25,5): error MSB4044: The "XamarinLiveTask" task was not given a value for the required parameter "CurrentDirectory".
```

**Comment by Adam--** [comment]
Also tried to move the config file to the same level as the .csproj for the PCL LiveXAML is installed in.

**Comment by ionoy** [comment]
The config file should be located at the *.csproj file directory. 

What version of LiveXAML are you using? It's very unusual that the task doesn't receive a CurrentDirectory value.

**Comment by Adam--** [comment]
The VS extension is 1.7.5

**Comment by Adam--** [comment]
Any updates on this? Is there anything I can do to help?

My current work around has been disabling the adapter and connecting. As you can imagine it's getting a little tedious.

**Comment by ionoy** [comment]
Did you try putting this file at the `*.csproj` file scope?

**Comment by Adam--** [comment]
Yes

**Comment by ionoy** [comment]
Please try replacing all the files in the `build` folder. Make sure you still have the `livexaml.config` file at the `*.csproj` level.

[build.zip](https://github.com/OYIon/LiveXAML/files/2202379/build.zip)

**Comment by Adam--** [comment]
I'm able to build and connect to the correct adapter using the linked build.zip. 
Sorry for the delayed response.

**Comment by Adam--** [comment]
See #44
