### ISSUE TITLE
LiveXAML in production binary

### ISSUE THREAD

**Issue by kevinvella** [OYIon/XamarinFormsLive#60]
I forgot to remove LiveXAML from the production release and i notice some interesting stuff.

With LiveXAML the production release file size increased about 27.5MB. From 40.3MB to 67.8MB for iOS. 
For android 28.44MB. From 54.62MB to 83.06MB

Also i submitted the app to the store and apple complained about the following:

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSAppleMusicUsageDescription key with a string value explaining to the user how the app uses this data.

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSSiriUsageDescription key with a string value explaining to the user how the app uses this data.

I know LiveXAML is not supposed to be in a production release, but could you shed some light into this. Thanks

**Comment by ionoy** [comment]
Hi @kevinvella!

LiveXAML uses reflection to access the network stuff (`Socket`, `TcpClient` etc). If you install LiveXAML package into Android or iOS project, it will automatically disable the linker. This means that the whole API surface gets compiled into the resulting assembly. I'm not sure about the warnings that iOS Store produces, but it's most likely the linker issue. 

You can check the compiled assembly with ILSpy or another decompiler to see that there is nothing fishy going on. The code is minimized, so it's a bit mangled, but you can see what types LiveXAML uses.

Mihhail

**Comment by kevinvella** [comment]
Hi @ionoy,

Thanks for the explanation :) 
I thought that this was a linker issue but wasn't sure.

Added the DISABLE_XAMARINFORMSLIVE compilation symbol. Testing the release version now

Kevin
