### ISSUE TITLE
Errors when update page

### ISSUE THREAD

**Issue by douglassimaodev** [OYIon/XamarinFormsLive#61]
Every time I do an update even with a default project I get the error: LiveXaml error object refer ence not set to an instance of an object.(normal xf project)
 Or: master and details must be set before adding MasterDetailPage to a container 
(prism template)  but after clicking ok button from alert error the changes are applied
![screenshot_20180731-114713](https://user-images.githubusercontent.com/14874566/43455947-71ce4254-94b9-11e8-8915-479e8044762d.jpg)
![smartselect_20180731-120323](https://user-images.githubusercontent.com/14874566/43455967-9613d5f2-94b9-11e8-886b-110a48911e98.jpg)

**Comment by ionoy** [comment]
Hello @douglassimaodev 

So you are saying this happens even in the default project? I've just created a new project, and it works fine for me. Can you send me the smallest project where this error occurs?

Thanks!

Mihhail

**Comment by warappa** [comment]
Hi @ionoy 
I have seen at least one of those error messages in every project I worked on (reproduceable), but the first one is the one I'm currently facing.
In output it writes "[0:] XL: InitializeComponent ", where after "InitializeComponent " the element should be printed but it isn't. Before that is prints "Updated element not found: <valid-absolute-path-to-xaml-file>"
It seems related to a flag in minified.cs "ElementFound" which is false in the error cases.
The exception itself comes from "a.GetType().GetFields()", where "a" is null (and not null-checked).

_But just after that_ it prints "XL: InitializeComponent full-qualified-type-name" of the xaml-file that it claimed wasn't found just before! So the UI refresh itself works (on 2nd try), so I ignored it hoping for it to get fixed. :)

IDE: VS 2017 15.8.1
Plugin: 1.7.5
NuGet: 2.1.36
XF: 3.1.0.697729, Android Project (SDK Oreo 8.1)
Used Visual Studio Emulator for Android for debugging (5" Marshmallow 6.0.0)

**Comment by ionoy** [comment]
Hey @warappa !

Thanks for the comprehensive report!

Do you also see "Reloading the current page" message?

EDIT: Could you post all "XL:" messages, by the way?

**Comment by ionoy** [comment]
I have uploaded version 2.1.41 to NuGet

Please try it to see if it resolves the issue

**Comment by warappa** [comment]
@ionoy 
Sorry for the long delay. 
Good news: this version fixed this problems for me!
Thank you for your quick fix!
