### ISSUE TITLE
Problems with Merged Dictionaries in Xamarin Forms 3.0+

### ISSUE THREAD

**Issue by Inrego** [OYIon/XamarinFormsLive#62]
I have a few different resource files (for styles and converters etc). and I merge them in App.xaml

Example:

GeneralStyles.xaml:

    <?xml version="1.0" encoding="UTF-8"?>
    <ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms" 
                        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                        x:Class="Plabra.Styles.GeneralStyles">
      <Color x:Key="BackgroundColor">WhiteSmoke</Color>
      <Color x:Key="PrimaryTextColor">Black</Color>
      <Color x:Key="BrightTextColor">White</Color>
      <Color x:Key="AccentColor">#e73138</Color>
      <Style TargetType="ContentPage" ApplyToDerivedTypes="True">
        <Setter Property="BackgroundColor" Value="{StaticResource BackgroundColor}" />
      </Style>
      <Style TargetType="Label">
        <Setter Property="TextColor" Value="{StaticResource PrimaryTextColor}" />
      </Style>
      <Style TargetType="Button">
        <Setter Property="BackgroundColor" Value="{StaticResource AccentColor}" />
        <Setter Property="TextColor" Value="{StaticResource BrightTextColor}" />
      </Style>
    </ResourceDictionary>

And App.xaml:

    <?xml version="1.0" encoding="utf-8" ?>
    <Application xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:styles="clr-namespace:Plabra.Styles;assembly=Plabra"
                 xmlns:converters="clr-namespace:Plabra.Converters;assembly=Plabra"
                 x:Class="Plabra.App">
      <Application.Resources>
        <ResourceDictionary>
          <ResourceDictionary.MergedDictionaries>
            <converters:Converters />
            <styles:GeneralStyles />
          </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
      </Application.Resources>
    </Application>

When making changes in GeneralStyles.xaml while debugging, I see that the page refreshes on the emulator, but it doesn't change the color.

**Comment by Inrego** [comment]
Ah, I just saw that this might be related to https://github.com/OYIon/LiveXAML/issues/38

**Comment by ionoy** [comment]
Thank you for the report! 

I have fixed this issue and will soon publish the updated NuGet package.

In the meantime you can use a workaround:

```
    <ResourceDictionary MergedWith="styles:GeneralStyles">
    </ResourceDictionary>
```

**Comment by Inrego** [comment]
Thanks, but AFAIK it's not possible to merge multiple resources with that syntax.

**Comment by ionoy** [comment]
Yep, that's why it's just a temporary workaround. I'll release the updated NuGet soon.
