### ISSUE TITLE
ResourceDictionary.MergedDictionaries

### ISSUE THREAD

**Issue by ederbond** [OYIon/XamarinFormsLive#70]
Just after installing LiveXaml nuget package I've started to receive the following build exception:
Resource 'Styles/Base/Colors.xaml' not found.

It causes my build to fail due to  appearently not finding a style file. But the file is there and it works just fine if I uninstall the LiveXaml nuget package

**Comment by ederbond** [comment]
![image](https://user-images.githubusercontent.com/12549812/50997113-e5287180-150a-11e9-9306-77fd0eada80b.png)

**Comment by ionoy** [comment]
One of the latest NuGet package releases should have fixed that. Would it be possible to remove all sensitive information from your project and send it to me so that I could reproduce the issue on my machine?

Thanks!

**Comment by ederbond** [comment]
The latest nuget package released just today didn't fixed this problem.

**Comment by ederbond** [comment]
What is your e-mail so I can send you a copy of my project.

**Comment by ionoy** [comment]
Hello @ederbond 

My email is `info@ammyui.com`

**Comment by ederbond** [comment]
@ionoy  I've sent you my source code by to the e-mail above on Mon, Jan 14, 6:42 AM
could you check that and let-me know if you received and could reproduce the error ?

**Comment by ionoy** [comment]
Yep, I'm already investigating the issue. Will reply soon.

Thanks!

**Comment by ederbond** [comment]
Any news about this ?

**Comment by ionoy** [comment]
Yes, I have already fixed the issue. Will release the update in a day or two.

**Comment by ederbond** [comment]
Please release the fix you have made for this...

**Comment by ionoy** [comment]
I'm still fixing some other stuff, so I can't make a full release. You can download a beta version though: https://www.nuget.org/packages/LiveXAML/2.1.62-beta

**Comment by ionoy** [comment]
Hello @ederbond 

I have published the 2.1.63 version of LiveXAML NuGet package. Please try updating and see if it works for you. 

Thanks!

**Comment by ederbond** [comment]
It worked! 
Thanks @ionoy
