### ISSUE TITLE
Return to the same location within Shell when updating a ContentPage

### ISSUE THREAD

**Issue by davidortinau** [OYIon/XamarinFormsLive#71]
Screencast: https://www.screencast.com/t/e3tyonTx2ek

The refresh on change always brings me back to the first ContentPage. Would be ideal to bring me back to the same page I'm editing.

Guessing at what you might need to do, maybe:

1. Use the Shell.CurrentItem
2. Use the navigation URI and trigger that upon reloading without animation.

@StephaneDelcroix may have other ideas. Likely better.

**Comment by StephaneDelcroix** [comment]
I think each page could be attributed with a "designUri" kind of attribute, so any previewer could ask the shell to navigate to that destination

**Comment by StephaneDelcroix** [comment]
CurrentItem would make a good fallback

**Comment by ionoy** [comment]
Hello David,

I have published the 2.1.63 version of LiveXAML NuGet package. Please try updating and see if it fixes the issue for you.

Thanks!

**Comment by davidortinau** [comment]
It's looking good, thanks!
