### ISSUE TITLE
Not reload update

### ISSUE THREAD

**Issue by ivanteles** [OYIon/XamarinFormsLive#79]
My PCL project does not use app.xaml.
I bought a license and still do not update on the device

LiveXAML: Application definition not found. 
1>C:\Users\ivan\.nuget\packages\livexaml\2.1.70\build\netstandard2.0\LiveXAML.targets(25,5): warning : * You should install LiveXAML package into the project with App.xaml
1>C:\Users\ivan\.nuget\packages\livexaml\2.1.70\build\netstandard2.0\LiveXAML.targets(25,5): warning : * You can uninstall LiveXAML from other projects
1>C:\Users\ivan\.nuget\packages\livexaml\2.1.70\build\netstandard2.0\LiveXAML.targets(25,5): warning : * For device debugging make sure to disable linking on platform projects

**Comment by aleksey-mondago** [comment]
Hi all. We bought the license as well and we have a similar issue here. 
Seems like LiveXaml doesn't see xamls when there's no App.xaml.

Here's my Xamarin.Forms project layout:

**App.iOS (ios app)**
  AppDelegate.cs etc.

**App.Android (android app)**
  MainActivity.cs etc.

**App.Portable (.net standard)** [references App.Views]
  App.xaml + App.cs

**App.Views (.net standard)**
  LoginView.xaml + cs
  SplashView.xaml + cs
  MainView.xaml + cs

Any workaround for this?

**Comment by ionoy** [comment]
@ivanteles 
You can use the following code to initialize without App.xaml
```
#if !DISABLE_XAMARINFORMSLIVE
    __livexaml.Listener.Initialize(null);
#endif
```

@aleksey-mondago 
Did you install `livexaml` NuGet package into both `App.Portable` and `App.Views` projects? 

Thanks,
Mihhail

**Comment by aleksey-mondago** [comment]
Hello, thanks, yes I did. When I build the project for say Android I get the following lines for App.Views project:

14>C:\Users\aleksey\.nuget\packages\livexaml\2.1.72\build\netstandard2.0\LiveXAML.targets(25,5): warning : LiveXAML: Application definition not found. 
14>C:\Users\aleksey\.nuget\packages\livexaml\2.1.72\build\netstandard2.0\LiveXAML.targets(25,5): warning : * You should install LiveXAML package into the project with App.xaml
14>C:\Users\aleksey\.nuget\packages\livexaml\2.1.72\build\netstandard2.0\LiveXAML.targets(25,5): warning : * You can uninstall LiveXAML from other projects
14>C:\Users\aleksey\.nuget\packages\livexaml\2.1.72\build\netstandard2.0\LiveXAML.targets(25,5): warning : * For device debugging make sure to disable 

I don't receive any further "[XL]" logs while debugging (I'm using VS 2019 if it's important)

**Comment by ionoy** [comment]
Are you calling `InitializeComponent` method in your App constructor? 

Additionally, you can try adding the code I provided to @ivanteles earlier. Just add it to your App constructor or anywhere during your app initialization.

**Comment by aleksey-mondago** [comment]
>Are you calling InitializeComponent method in your App constructor?

Apparently not. Hmm, it helped. Thanks!

**Comment by ionoy** [comment]
`InitializeComponent` is important. Otherwise, stuff in your App.xaml doesn't get invoked. It just so happens that LiveXAML uses App.xaml to initialize itself automatically.

**Comment by aleksey-mondago** [comment]
Yes, I agree it should be called. Thank you very much indeed

**Comment by ivanteles** [comment]
Solved!
