### ISSUE TITLE
Unable to find meta filename location

### ISSUE THREAD

**Issue by roubachof** [OYIon/XamarinFormsLive#8]
I have this error when I try to save the xaml after doing some changes.

![image](https://user-images.githubusercontent.com/596903/29451551-5c2ceee0-8403-11e7-8d17-8949b0f8c58c.png)

If i disable the extension, the error goes away :/
The project targets netstandard 1.6.

**Comment by ionoy** [comment]
Hello @roubachof,

1. What is your solution project structure? 
2. Is it a PCL or Shared project configuration? 
3. Do you have solution folders? 
4. Where are projects located on a disk relative to each other?
5. Does it happen only in debug mode?

Thanks for the feedback!

**Comment by roubachof** [comment]
hey,

1. here is my project structure
![image](https://user-images.githubusercontent.com/596903/29454715-7ac34254-840e-11e7-9fc7-ab40af8da500.png)

2. This is netstandard 1.6
3. Yes:
![image](https://user-images.githubusercontent.com/596903/29454781-b9f04698-840e-11e7-8efd-2855481c6e01.png)

4. you can see in 1.
5. At every save of the xaml (debug or not)

**Comment by ionoy** [comment]
It's possible, that this error is due to netstandard. I will try to fix it today.

Please just disable the extension for today, I will report back when you can update to a new version.

Thanks again!

**Comment by roubachof** [comment]
no problem, thank you for your quick answer.

**Comment by ionoy** [comment]
I have fixed this issue in the new VS Extension release. Make sure you have the latest version (1.3.19).

By the way, since you helped me to resolve an issue you are now eligible for a 30% discount if you ever decide to purchase a license.
