### ISSUE TITLE
Support for Visual Studio 2019 mac

### ISSUE THREAD

**Issue by henrik-stromberg-tetrapak** [OYIon/XamarinFormsLive#83]

**Comment by mshepher** [comment]
I also am unable to use LiveXAML following an update to the most recent main branch version of Visual Studio (VS 2019, 8.0.1).  lsof no longer shows LiveXAML listening on the necessary ports and I consistently get this error:

XL: =============== LiveXAML Important Information ===============
XL: Failed to find find a handshake server
1) Is phone connected to the same WiFi network?
2) Are ports 53031 and 53032 opened in firewall?
3) If On Windows, make sure that xlserver.exe is running
XL: ==============================================================

**Comment by jaykannan** [comment]
Anybody?

**Comment by ionoy** [comment]
Hello guys,

You can install the extension from the Visual Studio Extensions window. I will also soon upload the updated extension to www.livexaml.com

**Comment by ionoy** [comment]
I have added links to www.livexaml.com now.

**Comment by LuisDeHaro** [comment]
I'm seeing the same errors with:

Visual Studio Community 2019 for Mac
Version 8.1.5 (build 9)

----

XL: =============== LiveXAML Important Information ===============
XL: Failed to find find a handshake server
1) Is phone connected to the same WiFi network?
2) Are ports 53031 and 53032 opened in firewall?
3) If On Windows, make sure that xlserver.exe is running
XL: ==============================================================

Is VS 2019 Mac going to be supported? Just bought a one month license today hehe.
