### ISSUE TITLE
[Enhancement] Deploy core assembly in real time on Shared project build

### ISSUE THREAD

**Issue by GiampaoloGabba** [OYIon/XamarinFormsLive#84]
Hello, 
recently i came across a previewer for xaml that deploy the core assembly (.NET standard project) in real time (to emulators) when you hit the "compile" button". 

This is useful to test c# changes in a faster way than redeploy everything and start a new debug session.

It could be an awesome addition for LiveXaml :)

**Comment by ionoy** [comment]
Hello @Evolutionlab !

You can already use [LiveSharp](https://github.com/OYIon/LiveSharp) for that. It doesn't have the greatest documentation at the moment, but you can always visit https://gitter.im/LiveSharp/Lobby for the support.
