### ISSUE TITLE
LiveXAML should migrate to use AsyncPackage

### ISSUE THREAD

**Issue by Michael-Eng** [OYIon/XamarinFormsLive#86]
Microsoft will soon be releasing Visual Studio 2019 version 16.1. In 16.1, VS will stop auto-loading synchronous packages to improve startup performance. The recommendation is to switch to use asyncpackage or stop depending on auto-load of your VSPackage. 

More details can be found here:
[https://devblogs.microsoft.com/visualstudio/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/](https://devblogs.microsoft.com/visualstudio/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/
)

**Comment by ionoy** [comment]
Hello @Michael-Eng 

LiveXAML already uses `AsyncPackage`. Are you still experiencing this issue?

Thanks,
Mihhail
