### ISSUE TITLE
Stop working after using FFimageloading.forms in Xamarin project, Any workaround ?

### ISSUE THREAD

**Issue by anirugu** [OYIon/XamarinFormsLive#89]
just tried it again, look working. After having FFImageloading and using my own custom class it's not working. Any workaround?

**Comment by lhughey** [comment]
The product works with FFImageloading. Check the console for error messages and post back with more information.

**Comment by anirugu** [comment]
@lhughey  Thanks for reply. Can you just make a sampel demo so I can run on my machine and see if it's only related to my machine.

**Comment by ionoy** [comment]
Hello @anirugu 

Can you post the Output window log from the debugging session? I'm interested in lines starting with "XL:"
