### ISSUE TITLE
Installation issues on VS15.3

### ISSUE THREAD

**Issue by lhughey** [OYIon/XamarinFormsLive#9]
I've run into two issues when trying to install LiveXaml

1. The installation progress doens't reflect that the product is fully installed.  The installation bar hangs eventhough the product is installed.  I've replicated this 3 times on VS15.3

2. You cannot attempt to register the product more than once.  If your initial try fails, like mine did due to a restrictive company proxy, you are cannot attempt again. You will simply see the "accessed denied" HTML page from your proxy. I've tried uninstalling the extension a few times (I also removed the extension folder to ensure a clean install).  I also cleared my browser history . And, finally, I ensured a connection via an unrestricted hotspot.

The HTML output blows out the frame and your cannot get to the "start trial" button.  There is a button on the side (that is stretched), but it has no effect.  I have verified that I can browse to LiveXaml.com, so it is definitely cached.

I've attached a couple of screenshots to illustrate the issue. 
![notfinishinstall](https://user-images.githubusercontent.com/3799892/29621145-8b65f90a-87e5-11e7-8fbe-5d1fc698b823.png)
![oncechanceandyouredone](https://user-images.githubusercontent.com/3799892/29621146-8b685826-87e5-11e7-9e5c-8fa6a0bbb6aa.png)

**Comment by ionoy** [comment]
Hello Lyndon,

Thank you for the feedback!

I'm not sure what I can do with the first issue.  Are you sure it only happens with LiveXAML extension? There shouldn't be anything special about this installation.

As for the second one, it is definitely a bug. Please paste your Access Key here or send it to info@ammyui.com. I will send you your trial License Key back.

**Comment by lhughey** [comment]
Hello, ionoy.  You're correct.  The first issue seems to be a problem with my VS2017 15.3 installation.  I tried another extension and received the same result. 

Also, i was able to get around the 2nd issue by installing the product on VS2015, then deleting the content from the content box in Vs2017.  This caused the frame to resize appropriately, and I was able to paste in the key.

**Comment by ionoy** [comment]
Great!

Still, this is a great catch about the second issue. I will fix it in the new release.

As usual, since you posted this issue, I can offer you a good discount if you ever decide to purchase a license.
