### ISSUE TITLE
Throwing exception when saving changes changes

### ISSUE THREAD

**Issue by HobDev** [OYIon/XamarinFormsLive#91]
I am using Xamarin.Forms-4.1 for my project. The Shell is used for navigation. Whenever I am saving changes to the XAML file the following exception is being thrown:

System.Exception has been thrown.
Global routes currently cannot be the only page on the stack, so absolute routing to global routes is not supported. For now, just navigate to: company/sales/firstpage/

**Comment by ionoy** [comment]
Hello @HobDev 

Would it be possible for you to send the project reproducing the issue?
