### ISSUE TITLE
ComponentActivator: could not instantiate ViewModel

### ISSUE THREAD

**Issue by sadranyi** [OYIon/XamarinFormsLive#93]
I am using ASP.NET Zero Template for Xamarin Forms and I setup LiveXAML .
Changes are loading live but on any change i keep getting an Error stating ComponentActivator: could not instantiate ViewModel Error.

![image](https://user-images.githubusercontent.com/564700/61497596-89eea480-a9af-11e9-972c-83a56f94f634.png)

**Comment by ionoy** [comment]
Hello @sadranyi 

Please enable breaking on caught exceptions in the Exception Settings. This way you can see where the NullReferenceException occurs.

**Comment by divyesh008** [comment]
@sadranyi if you are using Grid in your page than change "Auto" to "*" for ColumnDefinitions and RowDefinations
