### ISSUE TITLE
[bug] Error hot reloading with named button

### ISSUE THREAD

**Issue by paul-charlton** [OYIon/XamarinFormsLive#94]
Hi,
I'm getting an error when a reload takes place and there's a button in the view that has a name using x:Name.  If it makes a difference I'm using ReactiveUI and the page inherits from ReactiveContentPage, but everything else is 'raw' Xamarin.Forms.

![image](https://user-images.githubusercontent.com/12197609/65030732-f1858980-d937-11e9-8f09-740b809d72df.png)

**Comment by ionoy** [comment]
Hello Paul,

I have just published the NuGet package update that should fix this issue.

Thanks,
Mihhail

**Comment by paul-charlton** [comment]
I can confirm that works - thanks.
